version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitOperationsProject
  gitServerName: testExtGit1
  gitUrl: https://github.com/PoojaAnandGit/GitOperationsProject
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.gitoperations.integrations:edgeflow1
  packages:
  - name: GitOperationsProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.866
- serviceName: project.gitoperations.integrations:newflow1
  packages:
  - name: GitOperationsProject
    version: "1.0"
